### ISSUE TITLE
Can't register new account via /v2/account/authenticate/email

### ISSUE THREAD

**Issue by botaoxu-grabtaxi** [heroiclabs/nakama#1087]
## Description
I can't register a new account by calling the endpoint http://localhost:7350/v2/account/authenticate/email
docker nakama version nakama:3.17.1

## Steps to Reproduce
request
`{
    "account": {
        "email": "aa.1023@gmail.com",
        "password": "12345678"
    },
    "username": "aa"
}`

## Expected Result
A new account with email aa.1023@gmail.com should be created.

## Actual Result
Get a HTTP 401 response as below
`{
    "code": 16,
    "message": "Server key required"
}`

**Comment by zyro** [comment]
@botaoxu-grabtaxi It would be very helpful if as part of the issue you shared how you're constructing the request (not just the body) because the response tells you exactly what you're missing - the server key is required as part of the `Authorization` request header.

I suggest making that change, and if you still have issues head over to [the forum](https://forum.heroiclabs.com/) for help. Even better would be to use one of the SDKs rather than constructing the request from scratch.

Either way this is not a server issue so will close. 🙇

**Comment by botaoxu-grabtaxi** [comment]
@zyro I am a little confused about why `Authorization` is required when creating a new account.
