### ISSUE TITLE
Trouble with Socket.AddMatchmakerAsync in Nakama Unity.

### ISSUE THREAD

**Issue by Its-Anonymous** [heroiclabs/nakama#1167]
Socket.AddMatchmakerAsync(“*” , 2, 4);

When using the Socket.AddMatchmakerAsync function with a minCount of 2 and a maxCount of 4, I’ve noticed that it behaves unexpectedly. Specifically, when three players request matchmaking, it only creates a match for two players. However, it works as expected when four players request matchmaking.

I’m curious to understand why this function seems to prioritize the minCount and maxCount exclusively, rather than accommodating an intermediate number of players between the specified range. If anyone has insights or suggestions on how to address this behavior, I would greatly appreciate the assistance. Thank you!

**Comment by zyro** [comment]
If the count multiple is set to `1` (the default) then a min/max of 2/4 can result in matches of 2, 3, or 4 players. The main variable will likely be when each player submits their ticket to the matchmaker relative to the matchmaker interval process.

It would help if you can provide a reproducible test case (as a `nakama-dotnet` test case perhaps?) that shows this unexpected behaviour, otherwise it's hard to help further. Feel free to re-open this issue with extra details as needed. 👍
