### ISSUE TITLE
Extending RoomsListing & Quick look at room users count without joining

### ISSUE THREAD

**Issue by xysverma** [heroiclabs/nakama#134]
As discussed with @novabyte on gitter. At present, thr is an easy way to get a chat topic last messages without joining it, however thr is no way to get actual number of users online in that topic without joining.

Use Case:
If a game wants to list game discussion topics without joining. This requires last few messages which is already available but additionally it also requires actual online user count to offer more info UI to users before joining the Topic & also to sort it based on number of users because it represents importance of those topics.

Extended Feature: Thr is a list of topics which constantly increase or decrease over time. If thr is a way to do a lightweight registration which gives realtime update of just user count in that room. 
e.g. We have listed Room A, B & C. Without joining the room, if we can update realtime update of number of users in those rooms, it would be a great addon.

**Comment by zyro** [comment]
This is possible since the addition of the [Streams API](https://heroiclabs.com/docs/advanced-streams/). You can [count presences](https://heroiclabs.com/docs/advanced-streams/#counting-stream-presences) to get the number of users in that chat channel and [list presences](https://heroiclabs.com/docs/advanced-streams/#listing-stream-presences) to get the full list of users currently in the channel.

The user does not need to actually join the channel, just call an RPC function that performs the operations above.
