### ISSUE TITLE
Expose metrics for Prometheus

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama#15]
Add a go-metrics sync for push/pull over socket to [Prometheus](https://prometheus.io/).

**Comment by julienBouysset** [comment]
Here are the metrics that might be helpful:
- Number of player connected / per server 
- Average connection time
- Average connection / per server 
- Number of games room
- momory / cpu

**Comment by novabyte** [comment]
Thanks @julienBouysset 😄

**Comment by julienBouysset** [comment]
New / Returning players - Shows the number of new (in red) and returning players (in blue).
Retention % by day - Shows the number of returning players as a percentage of the total players for a each day over the last 30 days.
Average Session Duration - Shows the average session duration in seconds.
Average DAU / MAU - Shows the average daily active player count over the monthly active player count. This is a measure of 'engagement'.
Devices - Shows the different devices that your players are using to play your game.
Players by Country - Shows the different countries where your game is being played.

**Comment by julienBouysset** [comment]
# Here is a list of more complete metrics.

New / Returning players - Shows the number of new and returning players.
Retention % by day - Shows the number of returning players as a percentage of the total players for a each day over the last 30 days.
Average Session Duration - Shows the average session duration in seconds.
Average DAU / MAU - Shows the average daily active player count over the monthly active player count. This is a measure of 'engagement'.
Devices - Shows the different devices that your players are using to play your game.
Players by Country - Shows the different countries where your game is being played.
Active Players Now - The total number of players that are currently connected to your game.
Daily Active Users (DAUs) - The total number of unique daily active players since midnight.
Average Daily Active Players (Avg DAUs) - A rolling average over the last 30 days for the DAU Big Number.
Monthly Active Users (MAUs) - Two metrics showing the total number of active players for last month and the current month.
Average Session Duration - The average player session duration for today.
Count - Shows the number of times a given custom key has been sent via the AnalyticsRequest..
Average Response Time (ms) - Shows the average response time (in milliseconds)
Average GO or Lua Execution Time (ms) - Shows the average time (in milliseconds)
Average Bandwidth per Player (bytes) - Shows the average amount of bandwidth per player that your game is using.

**Comment by novabyte** [comment]
@julienBouysset Some of these metrics are best solved as part of an analytics service. We'll have to analyse and split them out into those which could be handled by the game server and those which are a better fit for another system (and can be delivered to the external system via plugins https://github.com/heroiclabs/nakama/issues/12). It's a great list though. :smile:

**Comment by julienBouysset** [comment]
@novabyte Yes I understand but personally I do not know what metric will be better in a service. I will continue to add what I find interesting on this issue. You can tell me the metrics that are not in their place like that I will regroup and edit my messages.

**Comment by novabyte** [comment]
Initial metrics support via opencensus was added in 3afb6cd2124c8fdcb5e41774b2eaa552682864b5 for both Prometheus and Stackdriver.
