### ISSUE TITLE
Feature Request: Adding gluabit32

### ISSUE THREAD

**Issue by oott123** [heroiclabs/nakama#206]
https://github.com/BixData/gluabit32

It can add bitwise operator to the Lua Vm. It will be useful when using lua to play with binary data.

Let me know if this feature is ok to add and I can send a PR for you.

**Comment by novabyte** [comment]
@oott123 Nice request. This is already tracked on our roadmap although I've not yet updated the public plan since we released Nakama 2.0 yesterday. The problem I have with the BixData/gluabit32 implementation of the bitwise module backport for gopher-lua is that it doesn't implement the entire library of functions.

* Available:
    `"band"`, `"bnot"`, `"bor"`, `"bxor"`, `"lshift"`, and `"rshift"`.
* Not Available:
    `"arshift"`, `"btest"`, `"extract"`, `"replace"`, `"lrotate"`, and `"rrotate"`.

My concern is that if we don't backport the entire library we'll surprise users when they try to use functions which are described in the Lua manual but don't exist - https://www.lua.org/manual/5.2/manual.html#6.7

**Comment by oott123** [comment]
I should say you are right that this API is not same as the Lua native api.

Maybe we can provide it named other than `bit32`, for example, `bit42` or just `nk.bit32` ?
That's much better, because if whoever want to use it, he or she will check the docs to know the name, and have the knowledge about the API differences.

**Comment by novabyte** [comment]
@oott123 I'd prefer to let developers just import the library as though it's a standard library:

```lua
local bit32 = require("bit32")
```

But to do that we'll need a full implementation of all the bitwise library functions. I hope to tackle it in a couple of weeks time or could help sooner if you want to have a go at implementing it all as a Go package in the Nakama repo?

**Comment by oott123** [comment]
@novabyte Yes, you are right, a standard library like import is more better. But I have a little experience about GoLang, so I can only make small changes but not something like implementing a complete package. So let us keep this issue open until someone have some time to implement it.

**Comment by novabyte** [comment]
@oott123 No worries. Definitely we'll keep it open and tackle it.

**Comment by novabyte** [comment]
This was added in https://github.com/heroiclabs/nakama/commit/e54b956e3f2aa1eddb3b784ab26a6bd57d8e4d63 and will be part of the next release.
