### ISSUE TITLE
Send a notification to all clients in only one rpc call.

### ISSUE THREAD

**Issue by truonglvx** [heroiclabs/nakama#212]
In some cases, developer need an api to send a notification to all clients.

**Comment by mofirouz** [comment]
There are really two ways of achieving this (each with their own caveats), and I rule out the third way due to performance reasons.

1. Send a notification for each user in realtime, and store it in the database for each user for later retrieval if they are not online. This is exerts pressure on Nakama (less important), but more importantly puts *huge* write pressure on the database. Also, this isn't a trivial task to page through every user in the system. So this option is not good to use at all.

2. Use a stream/chat channel that every client would join at startup. You would then publish a non-persistant message to this channel. This of course means that only the players that are online would get the message.

3. You can use a client read-only storage object and persist your message in there. Clients would then list/read this storage object at start up time. The caveat here is that it is a pull model not a push model.

You can use both option 1 and 2 above together.

**Comment by zaniar** [comment]
@mofirouz Any chance we can get this feature out of the box? I believe it is common use case.

**Comment by novabyte** [comment]
@zaniar It's quite tricky to perform at scale because the player base could contain millions of users that would need a execute a streaming SQL query and distribute notifications in batches.

If you cannot wait you could implement the logic you need in Go which gives you the necessary tools to constrain the concurrency around the operation.
