### ISSUE TITLE
Feature: Set matchmaker's players by the server-side

### ISSUE THREAD

**Issue by inmylo** [heroiclabs/nakama#288]
## Description

Please add a way to set matchmaker's players by the server side. Currently every user sends his own params/filters for a match, then internally probably you take user's websocket connection object and put it to the matchmaking pool, at the end you send a response to this connection?!

I wish to be able to add players to the matchmaker's pool by the server, ideally by the WebSocket/HTTP request. For example, my custom service has a player's name "Player-A" and I wish to send it somehow to the matchmaker. At the end my service would get a list of chosen players by Nakama and a match ID, which I'll resend to the players.

Is that possible?

**Comment by novabyte** [comment]
Hi @imilo. The current matchmaker design is linked to clients so that the matchmaker can clean up entries as soon as client sockets are disconnected.

Do you want the option for the matchmaker not to observe client connections and therefore allow your own service to proxy back and forth between clients and the Nakama matchmaker? How would we clean up entries where the clients have been disconnected?

Perhaps it'd help to talk through the use case on the [community channel](https://gitter.im/heroiclabs/nakama).

**Comment by imilo** [comment]
"Do you want the option for the matchmaker not to observe client connections and therefore allow your own service to proxy back and forth between clients and the Nakama matchmaker" - yes. This middle service would be the only existing "client".

"How would we clean up entries where the clients have been disconnected?" - if player has disconnected after requesting for a new match - middle service will tell you who has disconnected (by ID or name, as it will know) and then you could remove him from the matchmaker's pool.

**Comment by novabyte** [comment]
After careful consideration @inmylo it doesn't make sense to matchmake players together without the socket presences marked by the matchmaker as we do today. We have introduced the concept of parties to the matchmaker which will be available in the 3.0 release of the server.

Have a look at this feature and I hope it can cover your use case.
