### ISSUE TITLE
Improve connectivity when enabling SSL in Nakama for development

### ISSUE THREAD

**Issue by nerdakos** [heroiclabs/nakama#348]
Hello everyone,
I try to connect from Unity Editor to nakama using SSL and what I get as a response from the server is the following:
_message: ApiResponseException(StatusCode=503, Message='all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs"', GrpcStatusCode=14)_

SSL is created using Lets Encrypt.

Client configuration: client = new Client("https",_ipAddress, 443, serverKey, UnityWebRequestAdapter.Instance) {

The Ip Address I used is the domain of my server.
I already tried running Nakama without SSL and it worked fine.'
Nakama Version: 2.5.1+8216d5cc
Cockroach version: v2.1.6

Any ideas?

**Comment by zyro** [comment]
I have an idea where the issue might be. If I put together a patched server build are you interested in testing it out @nerdakos?

**Comment by nerdakos** [comment]
Of course

**Comment by nerdakos** [comment]
@zyro are you going to send me the binary or you are planning to update the source code here?

**Comment by zyro** [comment]
If you're comfortable building from source I can put it on a branch of the repo here?

**Comment by nerdakos** [comment]
Once I am really new to Nakama, probably it would be better to share the binary with me. Thanks in advance!

On Jun 3, 2019 19:29, Andrei Mihu <notifications@github.com> wrote:

If you're comfortable building from source I can put it on a branch of the repo here?

**Comment by zyro** [comment]
I suspect the problem originates here and only surfaces under the Let's Encrypt certificates you're using, since we've used other SSL certificates successfully. The error indicates gRPC Gateway could not dial the gRPC server. https://github.com/heroiclabs/nakama/blob/cd34b7aaa914dfb583c5f76b9421a9e42e1a7196/server/api.go#L159
For now I recommend either setting up a more production-like SSL termination setup with a proxy or load balancer in front of Nakama, or experimenting with that code path yourself to find a fix - your help opening a PR for this would be very appreciated!

**Comment by fbcosentino** [comment]
I'm facing this issue using a Godot client (certificate is also from LetsEncrypt), is this issue still unsolved? Is there anything I can be doing on my side to sort this?

**Comment by CMattiske** [comment]
Same thing for me, ever since I used certbot (as suggested by LetsEncrypt) and added the certificates to my Nakama config, I get that same IP SANs error.

**Comment by novabyte** [comment]
@CMattiske can you share the start parameters you use with the game server and the specific error you observe in the server logs? Is it exactly the same as the one above in this issue?

**Comment by novabyte** [comment]
This is now solved in https://github.com/heroiclabs/nakama/commit/3e77583c8b1e4c829264bc6a32f264816f87549e. If you'd like to experiment ahead of the next server release have a look at the prerelease container image: https://hub.docker.com/r/heroiclabs/nakama-prerelease/tags

**Comment by CMattiske** [comment]
> @CMattiske can you share the start parameters you use with the game server and the specific error you observe in the server logs? Is it exactly the same as the one above in this issue?

My client initialisation code looks like this

`
const GCE_HOST: String = "www.cubedraftonline.com"

const SERVER_KEY: String = "cube_draft"
const SERVER_PORT_HTTP: int = 7350
const SERVER_SCHEME_HTTP: String = "http"
const SERVER_SCHEME_HTTPS: String = "https"

var _client: NakamaClient = Nakama.create_client(
	SERVER_KEY, GCE_HOST, SERVER_PORT_HTTP, SERVER_SCHEME_HTTPS)`

And the error on authentication is

{code: 14, message:connection error: desc = "transport: authentication handshake failed: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs"}

Which I think is identical. I'm hopeful about the fix you posted though, it looks promising.
