### ISSUE TITLE
Adding Achievement feature.

### ISSUE THREAD

**Issue by sabriboughanmi** [heroiclabs/nakama#349]
It will be Awesome if you guys Officially reimplement ACHIEVEMENTS again! ^_^

**Comment by AndreasBAT** [comment]
Hi there,

we are also interested in achievement support and I may potentially also attempt to implement it / help implementing it.

**Features we would like to be available**

* Achievements
  * Unique Identifier
  * Name
  * Description
  * Unlocked?
  * Revealed? (Whether it should be shown to the player, but they have not earned it yet)
  * Progress (some Achievements may be progressed towards, like total matches won, max total currency owned, etc)
    * Some may be progressive ones, like matches won
    * Others may be of the maximum value variety, like most currency owned
  * Achivements that have progress must also have an unlock value
  * Locked / unlocked image URLs
  * Unlock date
  * Auxilliary data field for custom game-specific stuff
    * One field per achievement
      *  Could allow for custom features like rarity levels (Bronze/Silver/Gold/whatever) or assigning a point value like GamerScore, Category, etc.
    * One field per player progressing towards it
      * e.g. URL to a screenshot or in case of a MOBA which hero was played
  * Possible future nice-to-haves
    * Rarity (Percentage of players having unlocked it)
    * Being able to earn an achievement multiple times
* Ability to define Achievements 
  * Best case via developer UI, otherwise via API by a server plugin (having this available to clients makes little sense to me)
* Updating / Unlocking achievements for a player
  * Should be available as an API to clients as well as to plugins
  * A future improvement may be the ability for game developers to restrict API availability to plugins only for security reasons 
* Querying all available achievements
* Querying achievements of a player
* Resetting specific achievements for a player

If anyone has further suggestions, please add them as well. I will evaluate whether and how I will proceed implementing an achievement system in the next days; can't promise though that something usable will come from it.

Kind regards

Andreas

**Comment by sthaiya** [comment]
Is there progress on this and when would we expect the feature.

**Comment by sthaiya** [comment]
And is there a simple workaround for now on achieving the same?

**Comment by novabyte** [comment]
@sthaiya This is not yet implemented. It's low priority for us because it's very easy to implement as a couple of RPC functions that write a storage object for the player. The logic is straightforward and we've never needed builtin support in Nakama. I can see why it would eliminate a small amount of code per game project which is why we've kept it on the roadmap.

**Comment by sthaiya** [comment]
Thanks for the prompt response. Could you point me to a sample RPC function to do this or sketch one for me? I am still new to nakama so dont have too much experience

**Comment by novabyte** [comment]
This is now available in [Hiro](https://heroiclabs.com/docs/hiro/concepts/) for use with Nakama server.

https://heroiclabs.com/docs/hiro/concepts/achievements/
