### ISSUE TITLE
metadata in group not saving from http request

### ISSUE THREAD

**Issue by cdiaz** [heroiclabs/nakama#360]
Metadata for a group is not being saved when the request is launched from curl, in the events to create and update group

**Comment by zyro** [comment]
Group and user metadata by design cannot be directly set by clients, only by the [server runtime](https://heroiclabs.com/docs/runtime-code-basics/).

We'll make this clearer in the documentation. Meanwhile if you've found anywhere in the docs where a code example updates metadata from the client please open an issue on the [docs repo](https://github.com/heroiclabs/nakama-docs).
