### ISSUE TITLE
Store handle for each user in the presence map

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama#39]
This was asked about on Gitter so that presence join and leave events can include the handle of the user who's state changed in the realtime chat or match.

**Comment by novabyte** [comment]
There's two ways I can think of what we could use to support this feature:

1. When a user joins their topics (both for chat and in matches) we could lookup their handle from the database and insert it alongside their record in the presence map as metadata. This could work well if all topic joins and leaves are done as single batch requests but become less performant if the user joins various topics in individual requests. This is also problematic with repeated disconnects by game clients on bad networks. We'd have to implement a cache of user accounts in memory to avoid thrashing the database.

2. We could cache the handle into the session token (JWT) so that after they login and get a session we can use that information when they connect to the game server over the socket. To mitigate (but not completely prevent) stale reads to their handle we could blacklist their session token when they update the handle in their profile. This will force the game client to relogin if the connection is lost and would give us an updated cached copy of the handle. The handle could still be stale over the lifetime of the socket connection if the client doesn't disconnect for some time.

Between these two options I lean towards option (2) it suffers from a small window of a stale cached view on a user's handle if they happen to update it within a socket's active lifetime but it doesn't cause performance implications to the database.

**Comment by julienBouysset** [comment]
2 :+1:

**Comment by zyro** [comment]
We also need to account for multiple devices/tokens per user, and potentially concurrent active sessions.

I agree on the tradeoffs for (1). Even after we add batch topic join/leave operations it'll be impossible to enforce the batching. Developers can still send individual operations if they choose, so we have to build with that case in mind.

My problem with (2) is putting configurable data in the tokens, rather than static identity and/or authorisation info. Config changes in one session would then require us to invalidate all tokens containing the stale config, including an arbitrary number of issued tokens that aren't currently connected.

Given this I think (1) is the better option, provided we also ensure all active presences for that user are updated. We have the added complexity of a caching layer to decrease the burden on the database, but we gain the option to enforce other per-user rules at session initialisation.

**Comment by zyro** [comment]
After further discussion on the semantics of accessing handles I'm now leaning towards option (2). The complexity involved in either managing the additional load on the DB or distributed caching is a wider problem and not worth it for handles in particular.

Other rules can be dealt with on a case by case basis, rather than bringing forward a lot of complexity before we need it.

**Comment by julienBouysset** [comment]
If solution 1 and more complex, but it is more relevant and this complexity can be reused future developments, it would be a pity to not develop this.

**Comment by zyro** [comment]
It's more complex, but the issue is it's not necessarily a net win. Access to handles can be done with solution (2) with no additional load on the DB, no distributed cache coordination, no increased network load between nodes, and maintains our ability to run realtime workloads when the DB is unavailable.

**Comment by saychong** [comment]
Option (1) seems more friendly for users to implement into their own projects, since i could already obtain the UserId, i should also be able to get other User related infos as well.

But after discussing with a senior of mine, we both agree that option (2) would be the better way to go. Do correct me if i am mistaken on this, from what we understand, option (1) seems to add a lot of burden to the DB, while option (2) would require less.

So i am also leaning more on option (2)

**Comment by novabyte** [comment]
@saychong Yep exactly. The second option removes the need to do a database lookup on each server socket connection. It also removes the need to run a distributed in-memory cache which would be the only way to avoid the additional database load. The moment we have a distributed cache we've got a complex cache invalidation problem to also need to solve. As mentioned above the tradeoffs are not worth it for just the user's handles in presence notifications in topics.

Other than the user's handle and ID what else would you want to be send over presence updates?

**Comment by saychong** [comment]
@novabyte for me, i require just the handle now, because its updated to the player "nickname" or "players name". 

But for future maybe it would be better if the return would be the whole ```INUser``` class itself? because i might be using the handle for the player name, but other devs might want to display other informations as well. Nonetheless, it would be up to you guys because i am lacking on the network knowledge side of things here.

**Comment by novabyte** [comment]
@saychong I think if game developers want to display more personal information in chat messages and realtime messages between users they can use our batch fetch functions to get a bunch of users in one go. They can also cache those records on the game client. Alternatively the chat messages themselves can contain the user's profile when the game client sends the message to the topic. We'll see if developers want more identifiable information in various parts of the realtime stream.

For now I think we're good to solve this problem just for the user's handle.

**Comment by novabyte** [comment]
Added in https://github.com/heroiclabs/nakama/commit/14cbcc78bed32d4a1fb4ba8e53584a7b6023b805.

You'll be able to see a user's handle in presence notifications (join/leave) as well as their ID. You'll need the latest Unity client which'll be released later today. /cc @julienBouysset @saychong
