### ISSUE TITLE
Feature: Allow matchmaking to take local players into account

### ISSUE THREAD

**Issue by JonathanPicques** [heroiclabs/nakama#397]
It would be nice to be able to enter the matchmaking as more than 1 player looking a match

The use case is local couch multiplayer games, where you can have 2 friends at home and want to play with 2 more players from elsewhere.

Suggestion:
```json
{
   "query": "*",
   "presences": 2,
   "min_count": 3,
   "max_count": 4
}
```

**Comment by novabyte** [comment]
@JonathanPicques The new party-based matchmaking option provides a way to match for multiple users under a single identifier. It's not a perfect solution because you'd need to open a socket for each of the local participants and have them join a party but after they're matched together you could then have the single socket drive all the netcode messages sent to other players in the match who are not local.
