### ISSUE TITLE
Request: InAppNotifications: add the id of the group

### ISSUE THREAD

**Issue by ooochris** [heroiclabs/nakama#411]
Looking at the "You've been accepted to X group."., the content contains the name of the group. It would be nice to also add the group id there.

Thanks

**Comment by zyro** [comment]
Each message is delivered on that group's channel ID, so you'll already know the group ID. This also applies to fetching message history - you'll know which group it is because you've specified its ID in the message history operation.

That said it might be useful to include the group ID explicitly in the message content so I'll leave this feature request open for now. :+1:

**Comment by ooochris** [comment]
I'm just doing a "ListNotificationsAsync" when I get back to the game. I don't think I can find it there. I may be wrong ofc.

**Comment by zyro** [comment]
Good point, that's outside the chat system so will need extra information. :+1:

**Comment by zyro** [comment]
Added in 92d944ffa5150ebc26d6a477197043fe5dda7cc0 and will be part of the next release.
