### ISSUE TITLE
No client notification on match end via runtime error

### ISSUE THREAD

**Issue by Superxwolf** [heroiclabs/nakama#414]
## Description
When a match ends abruptly due to a lua runtime error, Unity client receives no notification or indication the match has ended

## Steps to Reproduce
Create a match and join players. Have the match end due to lua runtime error. Notice on the client there are no messages or errors.

## Expected Result
Client receives an error message notifying match has ended.

## Actual Result
No error or notification, even when sending messages after match has ended.

## Context
- [ x] Unity
- [ ] Unreal
- [ ] Other

## Your Environment
- Nakama: 2.11.0
- Database: CockroachDB v19.2.4

**Comment by zyro** [comment]
Handled in dc8344386266976d4706b1d83d41f05adfa3b6e5 and will be part of the next release.

**Comment by Superxwolf** [comment]
To my understanding, the change seems to fully disconnect a socket on match error. Any reason why this was chosen instead of sending the socket an error message?

**Comment by zyro** [comment]
Yes there is a reason. For now this is the fastest way to get the desired effect across all client libraries until an appropriate callback can be added in the near future. Clients will reconnect and find the match is gone when they try to rejoin.

It's also worth noting that ideally match handler code should be robust enough not to throw unexpected errors. If it does this should be treated as a high priority bug to fix, rather than a scenario that should be accounted for as standard.
