### ISSUE TITLE
Realtime Match create error "attempt to modify read only table"

### ISSUE THREAD

**Issue by Superxwolf** [heroiclabs/nakama#437]
[modules.zip](https://github.com/heroiclabs/nakama/files/4848408/modules.zip)
## Description
There seems to be an issue with declaring functions inside a required lua module when creating a match using nk.match_create, giving the following error: "attempt to modify read only table".

This only occurs in Nakama 2.12, I have stayed in 2.11 as the error does not appear.

## Steps to Reproduce

I've added the nakama module files for a minimal replication of the issue, but essential it's just having the following code in realtime match:

Match.lua:
```
local other = require("other")

-- Rest of the match stuff
```

other.lua:
```
local t = {}

function ThisGeneratesTheError()

end

return t
```

## Expected Result
No errors should be thrown and match should initialize properly

## Actual Result
"attempt to modify read only table" with the function's start line as the culprit.

## Your Environment
- Nakama: 2.12
- Database: cockroach:v19.2.4
- Operating System and version: Windows 10 (Docker for Windows)

**Comment by zyro** [comment]
Nakama 2.12.0 added and enabled by default a new option:
> New option in Lua runtime for read-only globals to reduce memory footprint. This is enabled by default.

Your issue is declaring `function ThisGeneratesTheError()` as a global function. There are a couple of paths forward:
1. Declare it locally to the module as `local function ThisGeneratesTheError()`, potentially attach it to your returned module if needed as you do for match handler functions.
2. Disable the option for read-only globals with `--runtime.read_only_globals=false`. This will revert to the pre-2.12.0 handling of globals that you're used to, but you won't benefit from memory footprint improvements.
