### ISSUE TITLE
core_wallet.go logs non-errors at an error level

### ISSUE THREAD

**Issue by thegoldenmule** [heroiclabs/nakama#540]
## Description

When we look at our logs, we see a lot of error logs from wallet transactions that would put users at a negative balance (see https://github.com/heroiclabs/nakama/blob/master/server/core_wallet.go#L107). We would expect this to be logged at a lower level or not to be logged at all, as the error is returned and the caller can choose to log it.

Additionally, the case of a user having a negative balance should not be considered an error state.

## Workarounds

We have considered simply checking a user's balance before making transactions, but since there is no way to bundle the wallet query with a wallet transaction atomically (without mucking with `sql.DB` directly), it does not actually solve the problem. It seems that the correct way to consume this API is to attempt to make the transaction, and check the resulting error to disambiguate between a simple balance issue or a more serious internal error, like losing database connectivity.

**Comment by novabyte** [comment]
@thegoldenmule I think this complements this other issue: https://github.com/heroiclabs/nakama/issues/468. Both issues indicate the same root problem that we should improve in the next release of Nakama. We need to return a dedicated `error` type in Go and the other language runtimes when the wallet write is rejected because it would send the wallet into a negative balance. We'll also tidy up the logging around negative balances.

**Comment by thegoldenmule** [comment]
Thanks so much! Looks great.
