### ISSUE TITLE
Nakama server seems to drop clients around 2300~ concurrent users.

### ISSUE THREAD

**Issue by prodigga** [heroiclabs/nakama#60]
At around 2300~ users, the server seems to drop connections.

There seems to be no real errors on the server logs as to what causes this. The clients connected to the server receive exceptions once the 2300~ user mark is passed (Connections keep dropping until enough users are dropped and the number returns to around 2300~).

The exception seen on the clients is the following: `The header part of a frame cannot be read from a data source`.

Looking at the websocketsharp source code, that exception is thrown here:
https://github.com/sta/websocket-sharp/blob/079cd4db39abf65b6d810388a5cd0d61db460142/websocket-sharp/WebSocketFrame.cs#L428

Suggests that Nakama is responding to the clients request with a response that has the incorrect header length.

I have tested this on 2 server configurations - Amazon EC2 c4.xlarge, and c4.8xlarge.

The c4.xlarge servers stats:
7.5 GB RAM, 4 vCPUs, 'high' network performance.

The c4.8xlarge server stats:
60.0 GB RAM, 36 vCPUs, 10 Gigabit network connection

Both servers experienced the issue at around the same time in my tests. The c4.xlarge server saw around 85% utilisation at around the time of the problem. This led me to think that the server was just being overloaded. But the c4.8xlarge server experiences the same issue at about the same time, and the utilisation is at around 40% at that time.

I have provided a copy of the logs and my benchmarking code/tool to @mofirouz, along with instructions on how to reproduce the issue.

**Comment by novabyte** [comment]
Thanks for the detailed report @prodigga. I'll put together a benchmark workload for our internal harness which mirrors the layout of your experiment. See whether I can reproduce the behavior and we can address any client communication bottlenecks.

**Comment by zyro** [comment]
We've done a fresh round of benchmarking and we can't reproduce this behaviour. On a GCP n1-standard-1 (1 vCPU, 3.75 GB of RAM) running Ubuntu 16.04 LTS we got to ~11,000 CCU before we started hitting limitations in our test harness. It must be noted that the default network configuration needed a number of tweaks to reach this point.

@prodigga The root of your issue is likely the default system limits configuration on your VMs. If you're using Ubuntu on AWS EC2 the system limits will be the same regardless of the instance size, which will be why your issue appears at the same CCU point on both `c4.xlarge` and `c4.8xlarge`.

If you'd like to increase the load you put through a single node I recommend you tune the OS and network stack config. Pay particular attention to parameters like:

* `vm.swappiness` (should be `0`)
* `fs.file-max`
* `fs.nr_open`
* `net.ipv4.*` (especially `net.ipv4.ip_local_port_range`, `net.ipv4.tcp_mem`, `net.ipv4.tcp_rmem`, and `net.ipv4.tcp_wmem`)
* `net.core.*` (especially `net.core.rmem_default`, `net.core.rmem_max`, `net.core.wmem_default`, and `net.core.wmem_max`)

The exact values for these parameters depend on the instance size - mostly on the amount of available RAM - and the list here is not exhaustive.

Once we've made a number of additional improvements to our load test and benchmarking suite we'll be open-sourcing that to help others with the adjustments needed to reach very high per-node concurrency.

**Comment by thegoldenmule** [comment]
@zyro Are there any updates on releasing your load test and benchmarking suite for nakama?

**Comment by ATavanaei** [comment]
hi 
I need to know how many connections the Nakama server can support in one room.

**Comment by novabyte** [comment]
@ATavanaei This thread is 5 years old. A lot has changed and improved in Nakama. We have a [benchmarks page](https://heroiclabs.com/docs/nakama/getting-started/benchmarks/) which you can look at for information on the CCU that a single Nakama node can sustain. The exact CCU you can support will depend heavily on the hardware you use to run Nakama and the way it has been configured (ulimits, OS tuning, etc).
