### ISSUE TITLE
Runtime error when registering a RPC using typescript using a local variable for the id.

### ISSUE THREAD

**Issue by LucasGaspar** [heroiclabs/nakama#616]
## Description
When trying to register a RPC from the **InitModule** function using **TypeScript** using a local variable, Nakama reports an runtime error preventing it from running.

## Steps to Reproduce
This is from a _main.ts_ before compiling it to _index.js_ having a RPC function named _joinOrCreateMatch_ in another file.
This don't work:
```
function InitModule(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, initializer: nkruntime.Initializer)
{
    const JoinOrCreateMatchRpc = "JoinOrCreateMatchRpc";
    initializer.registerRpc(JoinOrCreateMatchRpc, joinOrCreateMatch);
}
```
This works:
```
function InitModule(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, initializer: nkruntime.Initializer)
{
    initializer.registerRpc("JoinOrCreateMatchRpc", joinOrCreateMatch);
}
```
This works too:
```
const JoinOrCreateMatchRpc = "JoinOrCreateMatchRpc";
function InitModule(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, initializer: nkruntime.Initializer)
{
    initializer.registerRpc("JoinOrCreateMatchRpc", joinOrCreateMatch);
}
```

## Expected Result
The function to be registered without a error.

## Actual Result
An runtime error that prevent Nakama from running.
```
{"level":"info","ts":"2021-05-18T20:42:01.084Z","caller":"server/runtime_javascript.go:523","msg":"Initialising JavaScript runtime provider","path":"/nakama/data/modules","entrypoint":""}
nakama_1       | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
nakama_1       |        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
nakama_1       |        panic: runtime error: invalid memory address or nil pointer dereference
nakama_1       | [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x180266f]
```

## Your Environment
- Nakama: 3.1.1
- Cockroach: 20.2

**Comment by sesposito** [comment]
@LucasGaspar thanks for the detailed report. 
I've improved the error handling so it doesn't panic with a nil dereference, however we won't support declaring the rpc id into a variable within the scope of the InitModule function at this time. I'd suggest you either use a string literal or set it into a variable declared in the global scope.

**Comment by LucasGaspar** [comment]
Ok, thanks! I think it could be added to the documentation to prevent confusion in the future @sesposito
Also could you explain to me why it doesn't work with a local scoped variable?

**Comment by sesposito** [comment]
We'll definitely improve the docs about this soon. I want to make clear that this specific caveat only applies to `initializer` functions that take some id (such as for rpc's registration) so you shouldn't worry about it in your actual JS logic. 

The reason it currently doesn't work is that to support a pool of JS virtual machines for improved performance, upon function registration in the InitModule, we need to do an AST traversal of the loaded JS code to keep track of the id these functions are registered with in the VM JS global object (this is also why anonymous functions are not supported, they have no id in the global object).

The issue lies in the AST traversal which would have to be able to resolve the value assigned to the variable you're passing to the registration in this specific edge case. It is possible to support it, and we might if it proves to be a real pain for developers, but for the time being we think the alternatives are well suited enough.

**Comment by LucasGaspar** [comment]
Thank you a lot for explaining it to me! Surely there is no need to fix it soon, the alternatives are pretty convenient.
