### ISSUE TITLE
[FEATURE] client API to list all the leaderboards

### ISSUE THREAD

**Issue by amirhoseinjfri** [heroiclabs/nakama#652]
hi 
for client side We don't have a client API yet which lets you list all the leaderboards . i personally need this for listing leaderboards and have it by sort i mean we get last leaderboard first and ... 
thnaks

**Comment by sesposito** [comment]
Hey @amirhoseinjfri 

You can use the [`LeaderboardList`](https://github.com/heroiclabs/nakama-common/blob/master/runtime/runtime.go#L941) function and set up a custom RPC. 

The function doesn't guarantee ordering but you can go over all the results and sort them however you like in your custom code.

Since this feature is already achievable, I'll close this issue.
