### ISSUE TITLE
(Groups) Kicking a requested user returns an error 

### ISSUE THREAD

**Issue by GPK42** [heroiclabs/nakama#66]
## Description
(Groups) Kicking a requested user returns an error "Could not kick user from group"
and on server logs:
"Could not kick user from group uid=5c96570d-726e-42e7-966c-ac7da2a4ac1a sid=32c36d15-b34c-4876-8283-ed779c5118c8 cid=d5705895-ba36-473d-b636-78f4ee77f409 group_id=57b38f3b-deb1-4ae5-ad02-ada89bc2ea9a user_id=fa6226f2-2a71-403a-ae67-9ce20d44769e error=pq: failed to satisfy CHECK constraint (count >= 0) stacktrace=goroutine 7397"

## Steps to Reproduce
Kick a user that has requested to join the group but isn't a member yet 

## Expected Result
remove the "join" user from the list of users 

## Actual Result
the requested user remains on the list 

## Context

- [ ] Unity

## Your Environment
name=nakama-a751 version=0.12.1+aab3e2e
`cockroach version` {"Version":1}

**Comment by zyro** [comment]
Looks like an issue in group kick where we incorrectly attempt to adjust the group member count when we remove a join request, which is not counted as part of the group `count` field.

This has also highlighted a separate issue where groups are incorrectly created with an initial count of `0`, instead of `1` to reflect the group creator as the first member. This does not affect core group functionality but should be fixed to show an accurate member count.

**Comment by zyro** [comment]
@GPK42 This is fixed in c6e3521a8590223be16cf08a0eaf2d1114be9afb and will be part of the next release of Nakama.
