### ISSUE TITLE
Bug in matchmaker causing relayed matches

### ISSUE THREAD

**Issue by mkieweg** [heroiclabs/nakama#761]
## Description

This bug appears when we want to use custom authoritative matches and matchmaking. It is easily reproducible by creating a Match module (in our case in Go, but as far as I can tell from reading the code Lua and TypeScript would behave the same) and starting a match using the matchmaker. This match cannot be joined by token but only by match id because the token [generates a new match id](https://github.com/heroiclabs/nakama/blob/491ddb2fd2e4b2dece650c15d509a3eb6f9c3ce7/server/matchmaker.go#L453) if no match id is returned by the module.

```go
		if !isMatchID {
			// If there was no callback or it didn't return a valid match ID always return at least a token.
			token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
				"mid": fmt.Sprintf("%v.", uuid.Must(uuid.NewV4()).String()),
				"exp": time.Now().UTC().Add(30 * time.Second).Unix(),
			})
			tokenOrMatchID, _ = token.SignedString([]byte(m.config.GetSession().EncryptionKey))
		}
```

This disassociates the generated match and the token. Since the token also doesn't contain a Nakama node joining a match using this token results in a newly created relayed match as tokens explicitly [allow empty relayed matches](https://github.com/heroiclabs/nakama/blob/491ddb2fd2e4b2dece650c15d509a3eb6f9c3ce7/server/pipeline_match.go#L162).

If the the boilerplate code [from the matchmaking documentation](https://heroiclabs.com/docs/nakama/concepts/server-authoritative-multiplayer/#matchmaker) is used and a match id is returned, no token gets generated. This directly contradicts [the documentation](https://heroiclabs.com/docs/nakama/concepts/matches/#join-a-match) which explicitly tells you to join the matchmade match using a token.

## Steps to Reproduce

1. Create a skeleton match module
2. Use boilerplate code from docs to register matchmaker matched
```go
func MakeMatch(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, entries []runtime.MatchmakerEntry) (string, error) {
    for _, e := range entries {
        logger.Info("Matched user '%s' named '%s'", e.GetPresence().GetUserId(), e.GetPresence().GetUsername())
        for k, v := range e.GetProperties() {
            logger.Info("Matched on '%s' value '%v'", k, v)
        }
    }

    matchId, err := nk.MatchCreate(ctx, "pingpong", map[string]interface{}{"invited": entries})
    if err != nil {
        return "", err
    }

    return matchId, nil
}
```
3. Token is empty
4. Return empty string in module
```
func MakeMatch(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, entries []runtime.MatchmakerEntry) (string, error) {
    for _, e := range entries {
        logger.Info("Matched user '%s' named '%s'", e.GetPresence().GetUserId(), e.GetPresence().GetUsername())
        for k, v := range e.GetProperties() {
            logger.Info("Matched on '%s' value '%v'", k, v)
        }
    }

    matchId, err := nk.MatchCreate(ctx, "pingpong", map[string]interface{}{"invited": entries})
    if err != nil {
        return "", err
    }

    return "", nil
}
```
5. Token contains unrelated match id and no Nakama node. Joining the match results in non-authoritative match

## Context

- [ ] Unity
- [ ] Unreal
- [x] Other (Server issue)

## Your Environment

- Nakama: Built from master branch
- Database: postgres
- Operating System and version: 5.10.60.1-microsoft-standard-WSL2

**Comment by zyro** [comment]
Hi @mkieweg, we've looked into this and the server behaviour is correct. Matchmaker matched client messages will contain either a match ID, or a match join token, but never both. This is expected and valid.

If the matchmaker matched hook returns a match ID, that indicates an authoritative match has been created or otherwise selected for use - the server will send that in the matchmaker matched client message **instead of** a token. For the purpose of matchmaker responses match IDs and match join tokens are mutually exclusive.

A matchmaker matched hook that returns an empty `""` match ID is functionally equivalent to having no matchmaker matched hook at all. The result will be the server assuming you want a relayed match, and generating a token to help achieve this. In your counter-example if you create an authoritative match but then never return its ID from the hook, the server cannot know that you intend to use this match for the users that have just been matchmade.

>If the the boilerplate code [from the matchmaking documentation](https://heroiclabs.com/docs/nakama/concepts/server-authoritative-multiplayer/#matchmaker) is used and a match id is returned, no token gets generated. This directly contradicts [the documentation](https://heroiclabs.com/docs/nakama/concepts/matches/#join-a-match) which explicitly tells you to join the matchmade match using a token.

You are however right, the documentation is not fully clear. We will improve this! 👍
