### ISSUE TITLE
Typescript environment should be fully reset at each RPC

### ISSUE THREAD

**Issue by gpiumatti** [heroiclabs/nakama#762]
## Description
Variables declared in the global scope in a Typescript script sometimes retain state from previous RPC executions.

## Steps to Reproduce
```typescript
function InitModule(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, initializer: nkruntime.Initializer): void {
    initializer.registerRpc('test', testRpc);
}

!InitModule && InitModule.bind(null);

const cache: { [k: string]: number } = {};

function testRpc(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string): string {
    const r = Math.random().toString();
    cache[r] = Math.random();
    logger.info(`added k = ${r} and v = ${cache[r]}`);
    return JSON.stringify(cache);
}
```

## Expected Result
RPC calls consistently return a JSON object with a single key-value pair.
i.e. variable `cache` is initialized at every RPC.

## Actual Result
RPC calls will eventually begin returning JSON objects with 2 keys, then 3 keys, etc.. The keys match those generated in previous RPC calls.

## Context

Server only

## Your Environment

- Nakama: 3.9.0

**Comment by sesposito** [comment]
We cannot reset the state of the VMs as it would hinder the advantages of the pooling we use to amortize the JS code interpretation time and allow concurrent request processing. We're working on a PR that will make the global state of the VMs immutable so that problems derived from global state mutation can be detected.
