### ISSUE TITLE
[FEATURE REQUEST] Allow setting targets in `send_match_state_async`

### ISSUE THREAD

**Issue by dominiks** [heroiclabs/nakama#791]
As implemented serverside for #59 it would be great if we could specify the recipient of a match state update when sending it from the client. Broadcasting packages to all users is the most used case but sometimes data should only be sent to specific clients (usually this is only used for host<->client communications, not client<->client when declaring one of the players the 'host' of the match.)

It is easy to add a `target` field to the payload of the data and let the clients filter out packages that were not meant for them, but the network traffic remains - and a small potential for giving data where it not belongs. Allowing the `target` field to be set by clients when sending the package would be especially helpful for indies who don't necessarily have the additional capacities to also implement the necesseray server side scripting to use the routing on the server api when they are instead using the client-relayed multiplayer.

**Comment by zyro** [comment]
The server already allows this, and by extension accepts this parameter through the client/socket API. It's possible you're using an outdated client library version, or one that has not been updated with this feature - can you please open an issue against the specific client library repo, rather than the server? Thanks @dominiks!

**Comment by dominiks** [comment]
Oh, I see. Thanks for the quick response!
