### ISSUE TITLE
Add VoiceChat for Unity

### ISSUE THREAD

**Issue by fingerx** [heroiclabs/nakama#82]
Add VoiceChat for Unity likes PhotonVoice. Thanks. This is very import for vr!

**Comment by novabyte** [comment]
@fingerx Thanks for the feature request. A voice chat system is definitely a feature we've considered. I'm not sure we'll build it into the core game server as it has very special requirements for API, network protocol, etc.

I'll leave this issue open as a tracker for the discussion on a voice chat server. 😄

**Comment by fingerx** [comment]
thanks @novabyte  .  photon voice using opus code，this is open source project.Hope info help nakama!

**Comment by martindevans** [comment]
I've just received a [feature request](https://github.com/Placeholder-Software/Dissonance/issues/37) on my own project ([Dissonance Voice Chat](https://www.assetstore.unity3d.com/en/#!/content/70078)) to add support for Nakama. Dissonance is designed to work with almost any network back end - all we need is a way to send UDP style packets (fast, lossy, out of order) - is it possible to do that with Nakama?

**Comment by novabyte** [comment]
Hi @martindevans I actually just looked at Dissonance the other day. I'd love to make an integration happen between our projects. It's a bit tricky right now with Nakama because we've not switched our network protocol over from fast TCP to a UDP-based protocol yet.

Would be interested to have a chat sometime next week if you can?

**Comment by martindevans** [comment]
> we've not switched our network protocol over from fast TCP to a UDP-based protocol yet.

I take it the plan is to use UDP (with some kind of rUDP?) for all traffic in the future? That'd be great for voice.

> Would be interested to have a chat sometime next week if you can?

Sure, contact martin@placeholder-software.co.uk whenever you like :)

**Comment by novabyte** [comment]
> I take it the plan is to use UDP (with some kind of rUDP?) for all traffic in the future? That'd be great for voice.

@martindevans Yes exactly. We started with fast TCP (quick ack + no delay) to focus on the design of the binary protocol with clients and have achieved performance we're very happy with. The next stage is to improve the network protocol with an optionally reliable UDP implementation.

> Sure, contact [email] whenever you like :)

Thanks. I'll drop you an email on Monday and we can chat. 😄

**Comment by fingerx** [comment]
Any News @novabyte ？ thanks

**Comment by novabyte** [comment]
@fingerx Not had the chance to have a chat with the Dissonance team yet. Like I mentioned we'll not add voice chat directly into the core game server because it's a very specialized system and not suitable to integrate. Is your game project live? What features of Nakama server do you use?

**Comment by martindevans** [comment]
> The next stage is to improve the network protocol with an optionally reliable UDP implementation.

We (the Dissonance team) are basically waiting for this. Once Nakama has a way to send low-latency, unreliable+unordered packets we should be able to build a network integration for Dissonance fairly quickly :)

**Comment by fingerx** [comment]
@novabyte  Thank you very much for your reply! My Project is live and voice chat is very important for me.
like @martindevans  said wating for your team said:"The next stage is to improve the network protocol with an optionally reliable UDP implementation."  Dissonance is very great assets. Hope to be updated as soon as possible. @novabyte   thanks again.

**Comment by martindevans** [comment]
Hi, I just thought I'd check in and see if there's been any progress on UDP in Nakama?

**Comment by AlimJaffer** [comment]
Hi @martindevans, perfect timing. With the 1.2 release of the server we added UDP support. 

You can read more about the UDP implementation in our [latest blog post.](https://blog.heroiclabs.com/nakama-1-2-released-udp-advanced-matchmaker-and-javascript-d9e9e46b6bd)

**Comment by martindevans** [comment]
I'm hoping to get around to implementing Dissonance for Nakama soon. Hopefully once it's done we can both benefit :)

Would anyone on the Nakama team be interested in collaborating with me on this? I can write the code for sending and receiving Dissonance voice packets no problem, but I guess I might need help with the best way to integrate with all the different Nakama concepts of rooms/identities/sessions/sockets etc.

**Comment by mofirouz** [comment]
Hey @martindevans - Ping us over at [Gitter](https://gitter.im/heroiclabs/nakama) to speak more.

**Comment by wikieden** [comment]
also quite interesting in this

**Comment by joshuawilde** [comment]
I am very interested in this. Currently using Photon Voice but would like to switch to Nakama. Has any progress been made here?

**Comment by martindevans** [comment]
I had a chat to the guys at Nakama earlier in the year but it was a really busy time for them and we decided to reconvene later in the year.

An integration for Nakama is going to be quite complex because some things don't quite fit how Dissonance works - e.g. a Nakama session can be huge but Dissonance can't practically handle such massive sessions with the default network backend. Also there were a few different levels at which you might want to do voice chat (e.g. chat to a single friend, chat to a group of friends, chat to your current game session) and in principle those could all happen at the same time, which Dissonance/Nakama should handle gracefully.

Right now the best way to do it (assuming your Nakama session are not huge) would probably be to build a custom backend (which doesn't have to deal with these issues, because you know the constraints your game is working within) or transmit the details of a session for another network system (e.g. [webrtc](https://assetstore.unity.com/packages/slug/143294?aid=1100lJDF) for peer to peer voice) through Nakama and then connect to that session just for voice chat.
